#!/usr/bin/env bash
bash -n "$0" | exit 1

# FDB deadlock testcase
################################################################################

# args
# <dbname> <dbdir> <testdir> <autodbname> <autodbnum> <cluster>
echo "main db vars"
vars="TESTCASE DBNAME DBDIR TESTSROOTDIR TESTDIR CDB2_OPTIONS CDB2_CONFIG SECONDARY_DBNAME SECONDARY_DBDIR SECONDARY_CDB2_CONFIG SECONDARY_CDB2_OPTIONS"
for required in $vars; do
    q=${!required}
    echo "$required=$q"
    if [[ -z "$q" ]]; then
        echo "$required not set" >&2
        exit 1
    fi
done

# Setup remote database
echo "Setting up remote database tables"
cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "CREATE TABLE t { $(cat t.csc2) }"
cdb2sql ${SECONDARY_CDB2_OPTIONS} $SECONDARY_DBNAME default "INSERT INTO t SELECT * FROM GENERATE_SERIES(1, 1000)"

# Setup local database
echo "Setting up local database tables"
cdb2sql ${CDB2_OPTIONS} $DBNAME default "CREATE TABLE t { $(cat t.csc2) }"
cdb2sql ${CDB2_OPTIONS} $DBNAME default "INSERT INTO t SELECT * FROM GENERATE_SERIES(1, 100)"

# Build and run the concurrent test
echo "Building deadlock test tool"
make fdb_deadlock_test

echo "Running concurrent foreign database access test"
./fdb_deadlock_test $DBNAME $CDB2_CONFIG $SECONDARY_DBNAME $SECONDARY_CDB2_CONFIG
result=$?

if (( $result != 0 )) ; then
   echo "Failure: deadlock test failed with exit code $result"
   exit 1
fi

echo "Success"
